version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8869:5432"
    volumes:
      - "./init/alexandrias.sql:/docker-entrypoint-initdb.d/1.sql"

